### ISSUE TITLE
资源何处？

### ISSUE THREAD

**Issue by vioulo** [lvyueyang/web-music#1]
其实感觉播放之类的技术相对简单，主要想问问资源能不能共享下？:dog:

**Comment by mintsweet** [comment]
....不会看 network 吗
....
....

**Comment by lvyueyang** [comment]
新的README已经更新，地址在下面，也可以直接查看源码获取

**Comment by lvyueyang** [comment]
@vioulo 我的资源也是在别的地方取得。这个项目的着重点在node端的代码实现与应用，本质上没有任何技术难点，初衷是为了能够更方便（免费）的听到周杰伦的歌曲。看到大家 star 之后给了我继续完善下去的动力。
