### ISSUE TITLE
打不开了 老哥 

### ISSUE THREAD

**Issue by 10wen** [lvyueyang/web-music#11]

**Comment by lvyueyang** [comment]
用 gitee 做的资源仓库，然后 gitee 给我封了，铁汁可以用**咪咕音乐**听周杰伦的歌，那里是免费的，我后期找找别的办法再维护下这个

**Comment by 10wen** [comment]
感谢 bro



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月30日(星期四) 中午11:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [lvyueyang/web-music] 打不开了 老哥  (Issue #11)





 
用 gitee 做的资源仓库，然后 gitee 给我封了，铁汁可以用咪咕音乐听周杰伦的歌，那里是免费的，我后期找找别的办法再维护下这个

**Comment by lvyueyang** [comment]
新版已经发布，可以再试试
