### ISSUE TITLE
感谢+添加歌曲

### ISSUE THREAD

**Issue by ISZayuu** [lvyueyang/web-music#12]
先感谢题主！！！！再就是轻轻问一句能不能加一首《我落泪情绪零碎》，真的很喜欢这首歌呜呜呜（能看得到嘛）

**Comment by lvyueyang** [comment]
这首歌已经在列表里面的，你可以直接搜索

**Comment by ISZayuu** [comment]
已经看到了，谢谢。



在 2023-03-03 14:07:57，"阿炸克斯" ***@***.***> 写道：

这首歌已经在列表里面的，你可以直接搜索
