### ISSUE TITLE
安卓手机via浏览器不能播放

### ISSUE THREAD

**Issue by hyshao** [lvyueyang/web-music#4]
表现为选完歌曲后，播放按钮跳了下变成了暂停，而且音乐进度条没有时长，会不会是因为这个https://github.com/DDFE/DDFE-blog/issues/24

**Comment by lvyueyang** [comment]
老哥换个浏览器吧

**Comment by hyshao** [comment]
hhhh，我刚才还以为是钓鱼软件，仔细一看才想起来jay这个项目


 
---原始邮件---
发件人: "阿炸克斯"<notifications@github.com&gt;
发送时间: 2019年12月9日 19:35:13
收件人: "lvyueyang/web-music"<web-music@noreply.github.com&gt;;
抄送: "hyshao"<1076973644@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [lvyueyang/web-music] 安卓手机via浏览器不能播放 (#4)



老哥换个浏览器吧

**Comment by lvyueyang** [comment]
新版已经重构，可以再试试，我试了试没问题
