### ISSUE TITLE
七牛资源应该是过期了，改一下downloadMusic.js代码

### ISSUE THREAD

**Issue by markjoker** [lvyueyang/web-music#7]
通过在线播放器的连接来下载是可以的，修改downloadMusic.js代码后再运行。

> function downloadFile(item, callback) {
    const uri = `http://jay-music.lvyueyang.top/${item.songid}.mp3`
    const name = `${item.title}.mp3`
    const stream = fs.createWriteStream(path.join(`./downloadFiles/${name}`))
    request(uri)
        .pipe(stream)
        .on('close', () => {
            callback ? callback(null) : true
        })
        .on('error', e => {
            callback ? callback(e) : true
        })
}

**Comment by lvyueyang** [comment]
大哥，求求你了，别批量下载了，就是个听歌得玩意儿，流量很贵的😭😭😭
